# Generated by Django 5.2.3 on 2025-08-06 07:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postcomment_postview_commentlike_postlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_method', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('copy_link', 'Copy Link'), ('direct_link', 'Direct Link')], max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('shared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='posts.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_shares',
                'indexes': [models.Index(fields=['post', '-shared_at'], name='post_shares_post_id_cfd88d_idx'), models.Index(fields=['user', '-shared_at'], name='post_shares_user_id_8f83e9_idx'), models.Index(fields=['share_method'], name='post_shares_share_m_c0eeae_idx')],
            },
        ),
    ]
