# Generated by Django 5.2.3 on 2025-08-06 07:29

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postshare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postshare',
            name='id',
        ),
        migrations.AddField(
            model_name='postshare',
            name='share_id',
            field=models.CharField(default=posts.models.generate_custom_id, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
