# Generated by Django 5.2.3 on 2025-08-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_postshare_id_postshare_share_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postshare',
            name='recipient_email',
        ),
        migrations.AlterField(
            model_name='postshare',
            name='share_method',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('copy_link', 'Copy Link'), ('direct_link', 'Direct Link')], max_length=20),
        ),
    ]
