# Generated by Django 5.2.3 on 2025-08-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_postshare_recipient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postshare',
            name='share_method',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('share_x', 'Share X'), ('linkedin', 'LinkedIn'), ('telegram', 'Telegram'), ('copy_link', 'Copy Link'), ('direct_link', 'Direct Link')], max_length=20),
        ),
    ]
