# Generated by Django 5.2.3 on 2025-08-07 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_postshare_share_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(help_text='Maximum 400 characters', validators=[django.core.validators.MaxLengthValidator(400)]),
        ),
    ]
