# Generated by Django 5.2.3 on 2025-08-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='subtitle',
        ),
    ]
