# Generated by Django 5.2.3 on 2025-08-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_room', '0002_remove_article_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, max_length=3500),
        ),
    ]
