# Generated by Django 5.2.3 on 2025-09-17 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVisit',
            fields=[
                ('visit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_visits', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_visits',
                'indexes': [models.Index(fields=['profile_owner', 'created_at'], name='profile_vis_profile_ead3ad_idx'), models.Index(fields=['visitor_ip', 'created_at'], name='profile_vis_visitor_385f80_idx')],
            },
        ),
    ]
