# Generated by Django 5.2.3 on 2025-08-21 20:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'ad_event_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdEvent',
            fields=[
                ('ad_event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('advertisement', 'Advertisement'), ('event', 'Event')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners/%Y/%m/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('draft', 'Draft')], default='active', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='ad_events.category')),
            ],
            options={
                'db_table': 'ad_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', 'status'], name='ad_events_type_18b061_idx'), models.Index(fields=['category'], name='ad_events_categor_993e2b_idx'), models.Index(fields=['start_date', 'end_date'], name='ad_events_start_d_d0873d_idx'), models.Index(fields=['location'], name='ad_events_locatio_cd8094_idx')],
            },
        ),
    ]
