# Generated by Django 5.2.3 on 2025-08-24 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('report_category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('fraud', 'Fraud'), ('harassment', 'Harassment'), ('misinformation', 'Misinformation'), ('hateful_speech', 'Hateful Speech'), ('self_harm', 'Self-harm'), ('scam', 'Scam'), ('sexual_content', 'Sexual Content'), ('infringement', 'Infringement'), ('spam', 'Spam'), ('illegal_goods', 'Illegal goods and services'), ('impersonation', 'Impersonation'), ('other', 'Other')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Report Categories',
                'db_table': 'report_categories',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('reason', models.TextField(blank=True, max_length=500)),
                ('object_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=1, help_text='1=Low, 2=Medium, 3=High')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.CharField(choices=[('none', 'No Action'), ('warning', 'Send Warning'), ('content_removal', 'Content Removal'), ('account_suspension', 'Account Suspension'), ('account_deactivation', 'Account Deactivation'), ('other', 'Other Action')], default='none', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.reportcategory')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'unique_together': {('reporter', 'content_type', 'object_id')},
            },
        ),
    ]
