# Generated by Django 5.2.3 on 2025-10-20 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_conversationdeletion_messagedeletion"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file_mime_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="message",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="message",
            name="file_size",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="message",
            name="is_compressed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="original_file_size",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="message",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="message_attachments/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "webp",
                            "mp4",
                            "mov",
                            "avi",
                            "mkv",
                            "webm",
                            "pdf",
                            "doc",
                            "docx",
                            "txt",
                            "xlsx",
                            "csv",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("file", "File"),
                    ("video", "Video"),
                    ("system", "System"),
                ],
                default="text",
                max_length=10,
            ),
        ),
    ]
